### ISSUE TITLE
Module initialization failed

### ISSUE THREAD

**Issue by dnbard** [alexkwolfe/json-fs-store#3]
```js
var store = require('store')('/storage');
```

Return `Error: Cannot find module 'store'` because in npm registry module stored as `node-store`.

```js
var store = require('node-store')('/storage');

store.add({"json": "valid"});
```

Return `TypeError: Cannot call method 'add' of undefined`.

OS: Win7

**Comment by Artanis** [comment]
Just ran into this, and in case @dnbard still needs it, or if anyone else runs into it, here is what's going on:

[`node-store`](https://www.npmjs.com/package/node-store) is a completely different module that appears to interact with mongodb. Further, [`store`](https://www.npmjs.com/package/store) is _also_ a completely different module, this time for localStorage.

Attempting to install this module with either its repository name, or its name according to `package.json` will thus resolve the wrong module.

Under further investigation, it seems that this module actually isn't registered on npm, [or at least, not by the author](https://www.npmjs.com/~alexkwolfe).

A workaround for this problem (assuming that the module hasn't been registered under a different name by someone other than the author), is to install the repository directly with `npm install https://github.com/alexkwolfe/node-store.git`.

**Comment by alexkwolfe** [comment]
Sorry I let this fall through the cracks. I'll rename the module, publish it to NPM, and update this issue when I'm done.

**Comment by ArekSredzki** [comment]
Please do :)

**Comment by ArekSredzki** [comment]
@alexkwolfe ?

**Comment by alexkwolfe** [comment]
This module has been renamed and [published to NPM](https://www.npmjs.com/package/json-fs-store). Again, my apologies for the delay.
