### ISSUE TITLE
the way to not specify a store directory

### ISSUE THREAD

**Issue by abulka** [alexkwolfe/json-fs-store#8]
I discovered that the way to be lazy and not specify an explicit store directory and get `json-fs-store` library to default to using the 'store' directory in the current directory is actually:

```
let store = require('json-fs-store')()
```
not simply
```
let store = require('json-fs-store')
```

those extra empty brackets are critical.  It might help if the readme documentation indicated this subtle distinction.  It stumped me for a while as I'm not used to requiring a module and calling it at the same time.

**Comment by alexkwolfe** [comment]
Resolved in 8f37ebabdef8c281d28306e23b2c6dd70813c917.
